sudo: required
language: rust

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  # check it compiles on the latest stable compiler
  - stable
  # Test for the minimum required version
  - 1.20.0

matrix:
  allow_failures:
    - rust: nightly

# the main build
script:
  - |
      rustc -vV &&
      cargo -vV &&
      cargo build &&
      cargo test &&
      cargo doc
